# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_name', models.CharField(max_length=30)),
                ('en_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_name', models.CharField(max_length=30)),
                ('en_name', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.CharField(choices=[('P', 'President'), ('VP', 'Vice-President'), ('SD', 'SalesDirector'), ('SM', 'SalesManager'), ('S', 'SalesMan')], default='S', max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('fixed', models.CharField(blank=True, max_length=30, null=True)),
                ('wechat', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
                ('cn_hscode', models.CharField(max_length=15, verbose_name='중국 HS CODE')),
                ('ko_hscode', models.CharField(max_length=15, verbose_name='한국 HS CODE')),
                ('etc_hscode', models.CharField(max_length=15, verbose_name='ETC HS CODE')),
                ('molnumber', models.CharField(max_length=100, verbose_name='분자량')),
                ('chemequal', models.CharField(max_length=100, verbose_name='화학식')),
                ('chemstructure', models.ImageField(blank=True, null=True, upload_to='', verbose_name='구조식')),
                ('usage', models.CharField(max_length=500, verbose_name='용도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_name', models.CharField(max_length=50)),
                ('en_name', models.CharField(max_length=50)),
                ('cn_address', models.CharField(blank=True, max_length=100, null=True)),
                ('en_address', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='tags',
            field=models.ManyToManyField(blank=True, to='products.Tag'),
        ),
    ]
