# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170628_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cn_name',
            field=models.CharField(max_length=30, verbose_name='CHINESE NAME'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='en_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENGLISH NAME'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cn_name',
            field=models.CharField(max_length=100, verbose_name='CHINESE NAME'),
        ),
        migrations.AlterField(
            model_name='product',
            name='en_name',
            field=models.CharField(max_length=100, verbose_name='ENGLISH NAME'),
        ),
        migrations.AlterField(
            model_name='product',
            name='etc_hscode',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ETC HS CODE'),
        ),
    ]
