# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_cas_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chemequal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='화학식'),
        ),
        migrations.AlterField(
            model_name='product',
            name='molnumber',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='분자량'),
        ),
    ]
