# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170628_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chemstructure',
            field=models.ImageField(blank=True, null=True, upload_to='chemicalstructure/', verbose_name='구조식'),
        ),
    ]
