# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170628_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='usage',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='용도'),
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Provider'),
        ),
    ]
