# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20170629_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/'),
        ),
    ]
