# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_provider_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='companytype',
            field=models.CharField(choices=[('T', 'TRADING'), ('M', 'MANUFACTURER')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='provider',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('I', 'INACTIVE'), ('B', 'BANKRUPT')], default='A', max_length=10),
        ),
    ]
