# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20170702_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='gprelation',
            field=models.CharField(choices=[('CURRENT', 'CURRENT'), ('OLD', 'OLD'), ('NO', 'NO')], default='CURRENT', max_length=20, verbose_name='GP RELATION'),
        ),
    ]
