# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20170702_0213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providerproduct',
            unique_together=set([('provider', 'product')]),
        ),
    ]
