# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20170702_0300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerproduct',
            options={'ordering': ['provider', 'product']},
        ),
        migrations.AddField(
            model_name='product',
            name='rate_taxrefund',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='RATE of TAX REFUND(%)'),
        ),
    ]
