# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20170702_0335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider',
            new_name='Vendor',
        ),
        migrations.RenameModel(
            old_name='ProviderProduct',
            new_name='VendorProduct',
        ),
        migrations.AlterModelOptions(
            name='vendorproduct',
            options={'ordering': ['vendor', 'product']},
        ),
        migrations.RenameField(
            model_name='vendorproduct',
            old_name='provider',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='contact',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorproduct',
            unique_together=set([('vendor', 'product')]),
        ),
    ]
