# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20170702_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['gprelation', 'cn_name']},
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='paytype',
            new_name='currency',
        ),
    ]
